"""inventory_processed_event create

Revision ID: 0c6e0845a2fd
Revises: 71bd8fb49b25
Create Date: 2026-06-01 18:47:57.787413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6e0845a2fd'
down_revision: Union[str, Sequence[str], None] = '71bd8fb49b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_processed_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_processed_events')
    # ### end Alembic commands ###
