"""outbox_events alter new column headers

Revision ID: ca24eae3fda8
Revises: 0c6e0845a2fd
Create Date: 2026-07-06 14:58:38.879212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca24eae3fda8'
down_revision: Union[str, Sequence[str], None] = '0c6e0845a2fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('headers', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'headers')
    # ### end Alembic commands ###
