global:
  scrape_interval: 5s

scrape_configs:
  - job_name: orders-service
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "outbox-worker"
    static_configs:
      - targets: ["order-outbox-worker:8001"]