server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker

    docker_sd_configs:
      - host: unix:///var/run/docker.sock

    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: "/(order-service|order-outbox-worker)"
        target_label: service
        replacement: "orders"
        action: replace

      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: "/(.*)"
        replacement: "$1"
        action: replace

      - target_label: job
        replacement: docker