"""outbox event retry_count next_attempt_at last_error updated_at fields

Revision ID: 3b49b9cdefab
Revises: b8e120d5a209
Create Date: 2026-06-01 13:08:07.210378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b49b9cdefab'
down_revision: Union[str, Sequence[str], None] = 'b8e120d5a209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE outbox_events")
    op.add_column('outbox_events', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('outbox_events', sa.Column('next_attempt_at', sa.DateTime(), nullable=True))
    op.add_column('outbox_events', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('outbox_events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'updated_at')
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'next_attempt_at')
    op.drop_column('outbox_events', 'retry_count')
    # ### end Alembic commands ###
