"""inventory processed events create

Revision ID: 6ab21b8adb2c
Revises: 1f34d8b74d1b
Create Date: 2026-07-05 17:40:48.670691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ab21b8adb2c'
down_revision: Union[str, Sequence[str], None] = '1f34d8b74d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_processed_events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_processed_events')
    # ### end Alembic commands ###
